--- !ditz.rubyforge.org,2008-03-06/project 
name: cl-gtk2
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cl-gtk2
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-10-01 19:39:12.427595 Z
    - Kalyanov Dmitry <Kalyanov.Dmitry@gmail.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-10-11 18:24:12.694312 Z
    - Kalyanov Dmitry <Kalyanov.Dmitry@gmail.com>
    - created
    - ""
